[phases.setup]
nixPkgs = ['nodejs_20', 'pnpm']

[phases.install]
cmds = [
  'pnpm install --frozen-lockfile',
  'cd backend && npm install && cd ..'
]

[phases.build]
cmds = [
  'npx tsc'
]

[start]
cmd = 'node frontend-server.js & cd backend && node server.js & node dist/index.js'

[variables]
NODE_ENV = 'production'