[phases.setup]
nixPkgs = ['nodejs_20', 'pnpm']

[phases.install]
cmds = [
  'pnpm install --no-frozen-lockfile',
  'cd backend && npm install && cd ..'
]

[phases.build]
cmds = [
  'npx tsc',
  'chmod +x start-all.sh'
]

[start]
cmd = 'sh start-all.sh'

[variables]
NODE_ENV = 'production'