"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.createAdminRoutes = void 0;
var hono_1 = require("hono");
var admin_js_1 = require("../controllers/admin.js");
var admin = new hono_1.Hono();
admin.get("/users", admin_js_1.getUsers);
admin.post("/users", admin_js_1.addUser);
admin.put("/users/:id", admin_js_1.editUser);
admin.patch("/users/:id/suspend", admin_js_1.suspendUser);
var createAdminRoutes = function () { return admin; };
exports.createAdminRoutes = createAdminRoutes;
